# Generated by Django 4.2.4 on 2023-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_index',
            field=models.IntegerField(default=0),
        ),
    ]
