# Generated by Django 4.2.4 on 2023-08-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_step_step_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='end_gif',
            field=models.URLField(default='https://media2.giphy.com/media/cQNRp4QA8z7B6/giphy.gif?cid=ecf05e47ohjkohlyjituly1p8eksruightei9lq4e60ghwoz&ep=v1_gifs_search&rid=giphy.gif&ct=g'),
        ),
        migrations.AddField(
            model_name='step',
            name='end_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='step',
            name='end_title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
