# Generated by Django 4.2.4 on 2023-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('newspaper_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
